version: "3.7"
services:
  app:
    image: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html